### ISSUE TITLE
Failed to get VM handle

### ISSUE THREAD

**Issue by caiovlp** [memflow/memflow-kvm#3]
I used to use vmread to read a win10 kvm on a arch 5.6 and it worked really well. I now have a fedora 5.9 and vmread doesn't seem to support it as it's been discontinued. I'm trying to get memflow kvm connector to work but keep getting:

inv: 0x258ec60
2020-12-17 16:28:48,922 ERROR [memflow_ffi::util] connector error: Failed to get VM handle
conn: (nil)

Not sure where to start looking into it. Tried running as root as well. Any ideas?

**Comment by h33p** [comment]
Hey, and welcome aboard! Did you install the memflow kernel module? Is it loaded? Does dmesg say smth in the lines of `memflow: initialized` when you load it? I know these are very basic, but worth mentioning.

What if you tried changing permissions with `sudo chmod 777 /dev/memflow`? If this works, it means it's just a permissions issue. Running as root should have worked, not sure why it didn't.

If nothing works, please let me know more about your setup, it should work on fedora :)

**Comment by h33p** [comment]
Closing as it appears inactive.
