### ISSUE TITLE
Events support 

### ISSUE THREAD

**Issue by VPaulV** [memflow/memflow-kvm#8]
I would like implement vmi-based debugger, but memflow doesn't support events handling (i.e. as libvmi do). I am considering to implement it myself, where could I start in this case? Do you have already some ideas in your mind on how it could be implemented? Probably we have already some kind of roadmap how it should be done for KVMi?

**Comment by h33p** [comment]
Yeah, debugging functionality is not something we have available at this current moment. There is a basic interface in mind available here: https://github.com/memflow/memflow/blob/main/memflow/src/connector/cpu_state.rs

However, we are no experts in debugging side of introspection and we haven't got around to starting proper design work as of yet. If you'd be willing to help on that, it would be great!

**Comment by VPaulV** [comment]
Alright, I guess I will jump in. Do you have any dev group somewhere where we could chat? Or I just write here if I have any questions regarding the current implementation?

**Comment by ko1N** [comment]
Currently we mainly use Discord for communication. You can find us in the [Memflow Discord Server](https://discord.gg/FNkVBGw8).
